#+TITLE: mq
#+DATE: 2019-06-26T09:49:02+01:00
#+DRAFT: false
#+CATEGORIES[]: about programs documentation projects
#+TAGS[]: mq perl6 maths

A command line program that tests your knowledge of arithmetic (addition/subtraction, multiplication/division),
and then logs the results, written in [[https://perl6.org/][Perl 6]], and licensed under the GNU GPL v3.0 (or any later version)

This document is about mq version 1.4.0, but the installation instructions will install the latest version

*Note*: =$MQ_CONFIG_DIR= was added in v1.4.0

* What is mq?
  mq is a program that asks you maths questions

* How to use?
  ~mq <mode> <max>~
  - Mode "level1" :: Addition, subtraction
  - Mode "level2" :: Multiplication, division
  - Mode "get-group" :: Get the group length
  - Mode "get-max" :: Get the maximum number
  - Optional named argument "disable-log" :: Disable the log file
  Example: ~mq --disable-log level1 10~

* Configuration file
** Where is the configuration file?
   If =$MQ_CONFIG= exists, then the config file is =$MQ_CONFIG=.\\
   If it does not exist, but =$MQ_CONFIG_DIR= exists then the config file is =$MQ_CONFIG_DIR/config.toml=.\\
   Otherwise, the config file is =~/.mq/config.toml= (default).

** What format is it in?
   It is written in TOML 0.4.0

** What keys/sections are there?
*** The section "mq"
    - The integer "group" :: The length of the group, can be set to any integer

** What does it look like?
   #+BEGIN_SRC toml
   [mq]
   group = 20
   length = 10
   #+END_SRC

* Log file
** Where is the log file?
   If =$MQ_LOG= exists, then the config file is =$MQ_LOG=.\\
   If it does not exist, but =$MQ_CONFIG_DIR= exists then the config file is =$MQ_CONFIG_DIR/log.slf=.\\
   Otherwise, the config file is =~/.mq/log.slf= (default).
** What format is it in?
   SLF (The Simple Log Format), basically CSV/DSV separated with spaces

* Installation instructions
  These instructions use GitHub, but you can use GitLab or Noisytoot Git instead, by replacing the URI you get mq from

** For UNIX and UNIX-like operating systems (like GNU/Linux, BSD, Mac OS X)
*** Using git
    Install mq:
    
    #+BEGIN_SRC shell
    cd ~
    git clone https://github.com/Noisytoot/mq.git
    cd mq
    ln -s $PWD/mq.p6 /usr/local/bin/mq # Replace /usr/local/bin/mq with where you want to install mq, you may need root permissions to run this
    mkdir ~/.mq
    #+END_SRC shell
    Update mq:
    
    #+BEGIN_SRC shell
    cd ~/mq
    git pull
    #+END_SRC shell

*** Using wget
    Install, and update mq:
    
    #+BEGIN_SRC shell
    cd /usr/local # Replace /usr/local with where you want to install mq
    wget https://raw.githubusercontent.com/Noisytoot/mq/master/mq.p6 -O mq # You may need root permissions to run this
    chmod +x mq
    #+END_SRC shell

** For other operating systems (like Windows)
   I do not currently have instructions for other operating systems,
   but basically you need to download mq.p6, add executable permissions if the OS has them, and put it into your PATH

[[https://github.com/Noisytoot/mq][GitHub]]
[[https://gitlab.com/noisytoot/mq][GitLab]]
[[https://git.noisytoot.org/noisytoot/mq][Noisytoot Git]]
